export const DATA_OF_COMPONY = {
  options: {},
  id: "d68e9cb7-c914-4e2a-88fd-589515d3da52",
  name: "Thinkitive Technologies Pvt",
  legalName: null,
  domain: "thinkitive.com",
  domainAliases: ["thinkitive.co", "thinkitive.net", "thinkitive.dev"],
  site: {
    phoneNumbers: [
      "+91 91727 53107",
      "+1 832-769-3856",
      "+44 1451 600818",
      "+34 518 88 84 13",
      "+1 405-638-3126",
      "+91 89567 75372",
    ],
    emailAddresses: ["hello@thinkitive.com", "sales@thinkitive.com"],
  },
  category: {
    sector: "Information Technology",
    industryGroup: "Software & Services",
    industry: "Internet Software & Services",
    subIndustry: "Internet Software & Services",
    gicsCode: "45102010",
    sicCode: "73",
    sic4Codes: ["7371"],
    naicsCode: "54",
    naics6Codes: ["541511"],
    naics6Codes2022: ["541511"],
  },
  tags: [
    "Information Technology & Services",
    "Computer Programming",
    "Software",
    "Professional Services",
    "Computers",
    "E-commerce",
    "Technology",
    "Consulting & Professional Services",
    "B2B",
    "B2C",
    "SAAS",
    "Enterprise",
  ],
  description:
    "Thinkitive is a software product development company that provides software technology solutions and services to startups and enterprises.",
  foundedYear: 2015,
  location: "3rd floor, Rohan Seher Ln, Baner, Pune, Maharashtra 411045, India",
  timeZone: "Asia/Kolkata",
  utcOffset: 5,
  geo: {
    streetNumber: null,
    streetName: "Rohan Seher Lane",
    subPremise: "3rd floor",
    streetAddress: "Rohan Seher Lane #3rd floor",
    city: "Pune",
    postalCode: "411045",
    state: "Maharashtra",
    stateCode: "MH",
    country: "India",
    countryCode: "IN",
    lat: 18.5557241,
    lng: 73.7731347,
  },
  logo: "https://logo.clearbit.com/thinkitive.com",
  facebook: {
    handle: null,
    likes: null,
  },
  linkedin: {
    handle: "company/thinkitive",
  },
  twitter: {
    handle: null,
    id: null,
    bio: null,
    followers: null,
    following: null,
    location: null,
    site: null,
    avatar: null,
  },
  crunchbase: {
    handle: null,
  },
  emailProvider: false,
  type: "private",
  ticker: null,
  identifiers: {
    usEIN: null,
    usCIK: null,
  },
  phone: null,
  metrics: {
    alexaUsRank: null,
    alexaGlobalRank: 552041,
    trafficRank: "medium_low",
    employees: 300,
    employeesRange: "251-1K",
    marketCap: null,
    raised: null,
    annualRevenue: null,
    estimatedAnnualRevenue: "$50M-$100M",
    fiscalYearEnd: null,
  },
  indexedAt: "2023-08-02T02:29:42.647Z",
  tech: [
    "amazon_s3",
    "outlook",
    "youtube",
    "godaddy_nameserver",
    "google_tag_manager",
    "google_apps",
    "microsoft_exchange_online",
    "nginx",
    "wordpress",
    "ubuntu",
    "google_maps",
    "hubspot",
    "google_analytics",
    "piwik",
    "klarna",
  ],
  techCategories: [
    "cloud_computing_services",
    "email_hosting_service",
    "image_video_services",
    "web_hosting",
    "tag_management",
    "productivity",
    "web_servers",
    "content_management_system",
    "operating_system",
    "geolocation",
    "marketing_automation",
    "analytics",
    "payment",
  ],
  parent: {
    domain: null,
  },
  ultimateParent: {
    domain: null,
  },
};
